"""Add token_family_id and device_id to refresh_tokens

Revision ID: f5e7752c5eca
Revises: f0f81bf68110
Create Date: 2025-10-21 18:57:25.821866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f5e7752c5eca'
down_revision = 'f0f81bf68110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_nullable=False)
    op.add_column('refresh_tokens', sa.Column('token_family_id', sa.String(length=255), nullable=False))
    op.add_column('refresh_tokens', sa.Column('device_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_refresh_tokens_token_family_id'), 'refresh_tokens', ['token_family_id'], unique=False)
    op.alter_column('user_companies', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_companies', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-10-21 21:28:42.062784+00'::timestamp with time zone"),
               existing_nullable=False)
    op.drop_index(op.f('ix_refresh_tokens_token_family_id'), table_name='refresh_tokens')
    op.drop_column('refresh_tokens', 'device_id')
    op.drop_column('refresh_tokens', 'token_family_id')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-10-21 21:28:42.062784+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###