"""add_supabase_fields_to_users

Revision ID: f0f81bf68110
Revises: 967855e4987d
Create Date: 2025-10-21 18:18:32.313090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0f81bf68110'
down_revision = '967855e4987d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_nullable=False)
    op.alter_column('user_companies', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_nullable=False)
    op.add_column('users', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'verified_at')
    op.alter_column('user_companies', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-10-21 14:49:13.985244+00'::timestamp with time zone"),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2025-10-21 14:49:13.985244+00'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###